import { Link } from 'react-router-dom'
import { Shield, BarChart3, Info } from 'lucide-react'

const DISCLAIMER = `CupCast provides match predictions for entertainment and informational purposes only. Predictions are generated by machine learning models trained on historical data and are not guaranteed to be accurate. CupCast does not operate as a sportsbook and does not accept wagers. Users are responsible for their own decisions. Please gamble responsibly. If you or someone you know has a gambling problem, contact the National Council on Problem Gambling at 1-800-522-4700.`

export default function Footer() {
  return (
    <footer className="border-t border-border mt-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 md:grid-cols-[1fr_auto] gap-8">
          {/* Disclaimer */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Shield className="w-4 h-4 text-foreground-muted" />
              <span className="cc-label">Disclaimer</span>
            </div>
            <p className="text-xs text-foreground-muted leading-relaxed max-w-2xl">
              {DISCLAIMER}
            </p>
          </div>

          {/* Links */}
          <div className="flex flex-col gap-2">
            <Link
              to="/about"
              className="flex items-center gap-2 text-xs text-foreground-muted hover:text-foreground transition-colors duration-200 cursor-pointer"
            >
              <Info className="w-3.5 h-3.5" />
              About
            </Link>
            <Link
              to="/model-performance"
              className="flex items-center gap-2 text-xs text-foreground-muted hover:text-foreground transition-colors duration-200 cursor-pointer"
            >
              <BarChart3 className="w-3.5 h-3.5" />
              Model
            </Link>
          </div>
        </div>

        {/* Bottom bar */}
        <div className="flex items-center justify-between mt-8 pt-4 border-t border-border/50">
          <p className="text-xs text-foreground-muted">
            &copy; {new Date().getFullYear()} CupCast
          </p>
          <p className="text-xs text-foreground-muted">
            Data from football-data.co.uk, Kaggle
          </p>
        </div>
      </div>
    </footer>
  )
}
