import { Link } from 'react-router-dom'
import { Brain, Database, Layers, Shield, Eye, AlertTriangle, ExternalLink } from 'lucide-react'

const DISCLAIMER = `CupCast provides match predictions for entertainment and informational purposes only. Predictions are generated by machine learning models trained on historical data and are not guaranteed to be accurate. CupCast does not operate as a sportsbook and does not accept wagers. Users are responsible for their own decisions regarding sports betting. Please gamble responsibly. If you or someone you know has a gambling problem, contact the National Council on Problem Gambling at 1-800-522-4700.`

const LEAGUES = [
  { name: 'English Premier League', country: 'England' },
  { name: 'English Championship', country: 'England' },
  { name: 'La Liga', country: 'Spain' },
  { name: 'Serie A', country: 'Italy' },
  { name: 'Bundesliga', country: 'Germany' },
  { name: 'Ligue 1', country: 'France' },
  { name: 'UEFA Champions League', country: 'Europe' },
]

const FEATURES = [
  'Team form over last 5 and 10 matches (win rate, goals scored/conceded)',
  'Home vs. away performance splits',
  'Head-to-head record between the two teams',
  'Rest days between matches',
  'League-wide averages (home advantage factor)',
  'Bookmaker odds (market consensus signal)',
  'Goal difference trends and scoring consistency',
]

function Section({ icon: Icon, title, iconColor = 'text-accent-blue', children }) {
  return (
    <section className="mb-10">
      <div className="flex items-center gap-3 mb-4">
        <div className={`w-8 h-8 rounded-btn flex items-center justify-center bg-white/5 ${iconColor}`}>
          <Icon className="w-4 h-4" />
        </div>
        <h2 className="text-h3 text-foreground">{title}</h2>
      </div>
      {children}
    </section>
  )
}

export default function About() {
  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-12">
      <h1 className="text-h1 mb-8">About CupCast</h1>

      <Section icon={Brain} title="What is CupCast?" iconColor="text-accent-gold">
        <p className="text-sm text-foreground-muted leading-relaxed">
          CupCast is an ML-powered soccer prediction platform. We analyze historical match data,
          team form, head-to-head records, and bookmaker odds to generate probability-based
          predictions for upcoming matches across major European leagues and the 2026 FIFA World Cup.
          Our goal is to give you a clear, data-driven perspective on match outcomes -- and
          highlight where the market may be mispriced.
        </p>
      </Section>

      <Section icon={Layers} title="How It Works" iconColor="text-accent-purple">
        <div className="space-y-3 text-sm text-foreground-muted leading-relaxed">
          <p>
            We train gradient-boosted decision tree models (XGBoost) on decades of match results
            across 6 major leagues. A separate international model handles national team predictions
            for the World Cup.
          </p>
          <p>
            For each upcoming match, the model outputs three probabilities: home win, draw, and
            away win. These sum to 100%. The predicted outcome is whichever has the highest
            probability.
          </p>
          <p>
            We then compare our probabilities to bookmaker odds. When our model disagrees
            significantly with the market (by more than 8%), we flag it as a{' '}
            <Link to="/value-picks" className="text-accent-gold hover:underline cursor-pointer">
              value pick
            </Link>{' '}
            -- not a guarantee, but a signal worth examining.
          </p>
        </div>
      </Section>

      <Section icon={Database} title="Features the Model Uses" iconColor="text-accent-green">
        <p className="text-sm text-foreground-muted mb-3">
          For each match, we compute approximately 60 features from historical data:
        </p>
        <ul className="space-y-2">
          {FEATURES.map((feature) => (
            <li key={feature} className="flex items-start gap-2 text-sm text-foreground-muted">
              <span className="w-1.5 h-1.5 rounded-full bg-accent-gold mt-2 flex-shrink-0" />
              {feature}
            </li>
          ))}
        </ul>
        <p className="text-sm text-foreground-muted mt-3">
          For international matches, additional features include FIFA ranking, ranking points,
          confederation, and tournament-specific adjustments.
        </p>
      </Section>

      <Section icon={Shield} title="Leagues Covered" iconColor="text-accent-blue">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {LEAGUES.map((league) => (
            <div key={league.name} className="cc-card p-4">
              <p className="text-sm font-medium text-foreground">{league.name}</p>
              <p className="text-xs text-foreground-muted mt-0.5">{league.country}</p>
            </div>
          ))}
        </div>
      </Section>

      <Section icon={ExternalLink} title="Data Sources" iconColor="text-foreground-muted">
        <ul className="space-y-3 text-sm text-foreground-muted">
          <li>
            Match results and bookmaker odds:{' '}
            <a
              href="https://www.football-data.co.uk"
              className="text-accent-blue hover:underline cursor-pointer"
              target="_blank"
              rel="noopener noreferrer"
            >
              football-data.co.uk
            </a>
          </li>
          <li>
            International match results:{' '}
            <a
              href="https://www.kaggle.com/datasets/martj42/international-football-results-from-1872-to-2017"
              className="text-accent-blue hover:underline cursor-pointer"
              target="_blank"
              rel="noopener noreferrer"
            >
              Kaggle (martj42)
            </a>
          </li>
          <li>
            FIFA world rankings:{' '}
            <a
              href="https://www.kaggle.com/datasets/cashncarry/fifaworldranking"
              className="text-accent-blue hover:underline cursor-pointer"
              target="_blank"
              rel="noopener noreferrer"
            >
              Kaggle (cashncarry)
            </a>
          </li>
        </ul>
      </Section>

      <Section icon={Eye} title="Model Transparency" iconColor="text-accent-purple">
        <p className="text-sm text-foreground-muted leading-relaxed">
          We publish our model's performance metrics openly on the{' '}
          <Link to="/model-performance" className="text-accent-blue hover:underline cursor-pointer">
            Model Performance
          </Link>{' '}
          page. This includes overall accuracy, F1 scores by outcome class, accuracy by league,
          and rolling 30-day accuracy. We believe in honest reporting -- including when draws
          are hard to predict (they always are).
        </p>
      </Section>

      {/* Legal Disclaimer */}
      <div className="cc-card p-6 border-accent-red/15">
        <div className="flex items-center gap-2 mb-3">
          <AlertTriangle className="w-4 h-4 text-accent-red" />
          <h2 className="text-sm font-semibold text-accent-red">Legal Disclaimer</h2>
        </div>
        <p className="text-xs text-foreground-muted leading-relaxed">
          {DISCLAIMER}
        </p>
      </div>
    </div>
  )
}
