"""initial schema

Revision ID: 4922171d5711
Revises: 
Create Date: 2026-04-20 10:37:24.831672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4922171d5711'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('season_format', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=50), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('f1_macro', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('team_type', sa.String(length=20), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('confederation', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('fifa_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.Column('fifa_rank', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'rank_date', name='uq_fifa_ranking_team_date')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=1), nullable=True),
    sa.Column('ht_home_goals', sa.Integer(), nullable=True),
    sa.Column('ht_away_goals', sa.Integer(), nullable=True),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('home_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('away_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.Column('home_fouls', sa.Integer(), nullable=True),
    sa.Column('away_fouls', sa.Integer(), nullable=True),
    sa.Column('home_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('away_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('home_red_cards', sa.Integer(), nullable=True),
    sa.Column('away_red_cards', sa.Integer(), nullable=True),
    sa.Column('kickoff_time', sa.String(length=10), nullable=True),
    sa.Column('tournament', sa.String(length=100), nullable=True),
    sa.Column('is_neutral_venue', sa.Boolean(), nullable=True),
    sa.Column('match_importance', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matches_away_team_date', 'matches', ['away_team_id', 'match_date'], unique=False)
    op.create_index('ix_matches_date_status', 'matches', ['match_date', 'status'], unique=False)
    op.create_index('ix_matches_home_team_date', 'matches', ['home_team_id', 'match_date'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_football_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('team_total_goals', sa.Integer(), nullable=True),
    sa.Column('goal_share', sa.Float(), nullable=True),
    sa.Column('is_key_player', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_football_id', 'season', name='uq_players_api_id_season')
    )
    op.create_index('ix_players_team_key', 'players', ['team_id', 'is_key_player'], unique=False)
    op.create_index('ix_players_team_season', 'players', ['team_id', 'season'], unique=False)
    op.create_table('team_name_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('injury_type', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_injuries_player_active', 'player_injuries', ['player_id', 'is_active'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prob_home_win', sa.Float(), nullable=False),
    sa.Column('prob_draw', sa.Float(), nullable=False),
    sa.Column('prob_away_win', sa.Float(), nullable=False),
    sa.Column('predicted_result', sa.String(length=1), nullable=False),
    sa.Column('predicted_home_goals', sa.Float(), nullable=True),
    sa.Column('predicted_away_goals', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('odds_home', sa.Float(), nullable=True),
    sa.Column('odds_draw', sa.Float(), nullable=True),
    sa.Column('odds_away', sa.Float(), nullable=True),
    sa.Column('edge_home', sa.Float(), nullable=True),
    sa.Column('edge_draw', sa.Float(), nullable=True),
    sa.Column('edge_away', sa.Float(), nullable=True),
    sa.Column('is_value_pick', sa.Boolean(), nullable=True),
    sa.Column('value_pick_direction', sa.String(length=1), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'model_version', name='uq_prediction_match_model')
    )
    op.create_index('ix_predictions_is_value_pick', 'predictions', ['is_value_pick'], unique=False)
    op.create_index('ix_predictions_match_id', 'predictions', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_match_id', table_name='predictions')
    op.drop_index('ix_predictions_is_value_pick', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_player_injuries_player_active', table_name='player_injuries')
    op.drop_table('player_injuries')
    op.drop_table('team_name_aliases')
    op.drop_index('ix_players_team_season', table_name='players')
    op.drop_index('ix_players_team_key', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_matches_home_team_date', table_name='matches')
    op.drop_index('ix_matches_date_status', table_name='matches')
    op.drop_index('ix_matches_away_team_date', table_name='matches')
    op.drop_table('matches')
    op.drop_table('fifa_rankings')
    op.drop_table('teams')
    op.drop_table('model_registry')
    op.drop_table('leagues')
    # ### end Alembic commands ###
